ARG VERSION
FROM 717232957798.dkr.ecr.us-west-2.amazonaws.com/argocd-lovely-plugin:rebase-base as source
FROM alpine:3.17.2
COPY --from=source /usr/local/bin/argocd-lovely-plugin .
USER 999
ENTRYPOINT [ "cp", "argocd-lovely-plugin", "/custom-tools/" ]
